---
name: Test
on:
  pull_request: []
  push:
    tags-ignore: ['*']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Setup Task
        uses: arduino/setup-task@v1

      - name: Run test task
        run: task test
